Ag/refactoring/clean architecture pattern
andriy1507/WeatherApp pull request #9
Opened 2020-01-31 10:23 UTC by andriy1507

Please, check is it correct or not.

2020-01-31 11:00 UTC, EugeneKryvoshey requested changes

2020-01-31 11:00 UTC, EugeneKryvoshey commented on remote/src/main/java/com/goryachok/remote/model/RemoteEntity.kt
> +abstract class RemoteEntity : Type {
Please, use type 'interface' and remove inheritance.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on remote/src/main/java/com/goryachok/remote/model/Main.kt
> +data class Main(
Please inherit this class from 'RemoteEntity'.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on remote/src/main/java/com/goryachok/remote/model/Forecast.kt
> +data class Forecast(
Please inherit this class from 'RemoteEntity'.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on remote/src/main/java/com/goryachok/remote/model/Coordinates.kt
> +data class Coordinates(
Please inherit this class from 'RemoteEntity'.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on remote/src/main/java/com/goryachok/remote/model/City.kt
> +data class City(
Please inherit this class from 'RemoteEntity'.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on local/src/main/java/com/goryachok/local/LocalDataSource.kt
> +    val preferences:SharedPreferences
Please, don't use public fields in interface unless you have to retrieve this data from implemented object.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on repository/src/main/java/com/goryachok/repository/WeatherRepository.kt
> +    val local: LocalDataSource
Please remove this.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on repository/src/main/java/com/goryachok/repository/WeatherRepository.kt
> +    val remote: RemoteDataSource
Please remove this.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on repository/src/main/java/com/goryachok/repository/ForecastRepository.kt
> +    val local: LocalDataSource
Please remove this.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on repository/src/main/java/com/goryachok/repository/ForecastRepository.kt
> +    val remote: RemoteDataSource
Please remove this.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on repository/src/main/java/com/goryachok/repository/WeatherRepository.kt
> +    fun isFetchNeeded(): Boolean
Please remove this.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on repository/src/main/java/com/goryachok/repository/ForecastRepository.kt
> +    fun isFetchNeeded(): Boolean
Please remove this.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on remote/src/main/java/com/goryachok/remote/model/Wind.kt
> +data class Wind(
Please inherit this class from 'RemoteEntity' interface.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on remote/src/main/java/com/goryachok/remote/model/Weather.kt
> +data class Weather(
Please inherit this class from 'RemoteEntity' interface.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on remote/src/main/java/com/goryachok/remote/RemoteDataSource.kt
> +    val api: WeatherApiService
Please remove this.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on local/src/main/java/com/goryachok/local/model/LocalWeather.kt
> +data class LocalWeather(
Please, rename to WeatherLocal.

2020-01-31 11:00 UTC, EugeneKryvoshey commented on local/src/main/java/com/goryachok/local/model/LocalData.kt
> +interface LocalData
Please rename to LocalEntity

2020-01-31 11:00 UTC, EugeneKryvoshey commented on local/src/main/java/com/goryachok/local/LocalDataSource.kt
> +    fun isDataAvailable(): Boolean
Please remove this.

2020-01-31 14:44 UTC, andriy1507 commented on remote/src/main/java/com/goryachok/remote/model/RemoteEntity.kt
> +abstract class RemoteEntity : Type {
Done

2020-01-31 14:45 UTC, andriy1507 commented on local/src/main/java/com/goryachok/local/LocalDataSource.kt
> +    val preferences:SharedPreferences
Fixed

2020-01-31 14:45 UTC, andriy1507 commented on repository/src/main/java/com/goryachok/repository/WeatherRepository.kt
> +    val local: LocalDataSource
Done

2020-01-31 14:45 UTC, andriy1507 commented on repository/src/main/java/com/goryachok/repository/WeatherRepository.kt
> +    val remote: RemoteDataSource
Done

2020-01-31 14:46 UTC, andriy1507 commented on repository/src/main/java/com/goryachok/repository/ForecastRepository.kt
> +    val local: LocalDataSource
Done

2020-01-31 14:46 UTC, andriy1507 commented on repository/src/main/java/com/goryachok/repository/ForecastRepository.kt
> +    val remote: RemoteDataSource
Done

2020-01-31 14:46 UTC, andriy1507 commented on repository/src/main/java/com/goryachok/repository/WeatherRepository.kt
> +    fun isFetchNeeded(): Boolean
Done

2020-01-31 14:46 UTC, andriy1507 commented on repository/src/main/java/com/goryachok/repository/ForecastRepository.kt
> +    fun isFetchNeeded(): Boolean
Done

2020-01-31 14:46 UTC, andriy1507 commented on remote/src/main/java/com/goryachok/remote/RemoteDataSource.kt
> +    val api: WeatherApiService
Done

2020-01-31 14:47 UTC, andriy1507 commented on local/src/main/java/com/goryachok/local/model/LocalWeather.kt
> +data class LocalWeather(
Done

2020-01-31 14:48 UTC, andriy1507 commented on local/src/main/java/com/goryachok/local/model/LocalData.kt
> +interface LocalData
Done

2020-01-31 14:48 UTC, andriy1507 commented on local/src/main/java/com/goryachok/local/LocalDataSource.kt
> +    fun isDataAvailable(): Boolean
Done

2020-01-31 14:48 UTC, andriy1507 commented
Maybe better is to make all remote data classes inner?

2020-01-31 15:21 UTC, EugeneKryvoshey requested changes

2020-01-31 15:21 UTC, EugeneKryvoshey commented on repository/src/main/java/com/goryachok/repository/di/RepositoryComponent.kt
> +    fun inject(repo: ForecastRepository)
Please remove this.

2020-01-31 15:21 UTC, EugeneKryvoshey commented on repository/src/main/java/com/goryachok/repository/di/RepositoryComponent.kt
> +    fun inject(repo: WeatherRepository)
Please remove this.

2020-01-31 15:24 UTC, andriy1507 commented on remote/src/main/java/com/goryachok/remote/model/Main.kt
> +data class Main(
Done

2020-01-31 15:24 UTC, andriy1507 commented on remote/src/main/java/com/goryachok/remote/model/Forecast.kt
> +data class Forecast(
Done

2020-01-31 15:24 UTC, andriy1507 commented on remote/src/main/java/com/goryachok/remote/model/Coordinates.kt
> +data class Coordinates(
Done

2020-01-31 15:24 UTC, andriy1507 commented on remote/src/main/java/com/goryachok/remote/model/City.kt
> +data class City(
Done

2020-01-31 15:24 UTC, andriy1507 commented on remote/src/main/java/com/goryachok/remote/model/Wind.kt
> +data class Wind(
Done

2020-01-31 15:24 UTC, andriy1507 commented on remote/src/main/java/com/goryachok/remote/model/Weather.kt
> +data class Weather(
Done

2020-02-03 12:11 UTC, EugeneKryvoshey approved these changes

2020-02-03 12:11 UTC, merged